# Encontro 8: Centro e Periferia
## Elisa Malzoni e Bruna Kimura

In [1]:
import sys
sys.path.append('..')

from random import choice
from itertools import permutations
from scipy import stats

import pandas as pd
import networkx as nx

import socnet as sn

In [2]:
sn.node_size = 10
sn.node_color = (255, 255, 255)

sn.edge_width = 1
sn.edge_color = (192, 192, 192)

sn.node_label_position = 'top center'

In [3]:
g = sn.load_graph('Renaissance.gml', has_pos=True)

sn.show_graph(g, nlab=True)

In [4]:
def set_geodesic_successors(g, s, t):
    for n in g.nodes:
        g.nodes[n]['geodesic_successors'] = set()

    for p in nx.all_shortest_paths(g, s, t):
        for i in range(len(p) - 1):
            g.nodes[p[i]]['geodesic_successors'].add(p[i + 1])

In [5]:
# Pense que o atributo 'passages' abaixo indica quantas
# vezes um fluxo já passou por um nó ou por uma aresta.

def random_geodesic_successor(g, n):
    return choice([m for m in g.nodes[n]['geodesic_successors']])

def random_path_successor(g, n):
    return choice([m for m in g.neighbors(n) if g.nodes[m]['passages'] == 0])

def random_trail_successor(g, n):
    return choice([m for m in g.neighbors(n) if g.edges[n, m]['passages'] == 0])

def random_walk_successor(g, n):
    return choice([m for m in g.neighbors(n)])

In [6]:
def simulate_single_flow(g, s, t, func_traj, difusao):
    # Inicializa o atributo 'passages' de cada nó.
    for n in g.nodes:
        g.nodes[n]['passages'] = 0
    g.nodes[s]['passages'] = 1

    # Inicializa o atributo 'passages' de cada aresta.
    for n, m in g.edges:
        g.edges[n, m]['passages'] = 0

    # Inicializa s como o único dono do insumo.
    for n in g.nodes:
        g.nodes[n]['owner'] = False
    g.nodes[s]['owner'] = True

    # Simula o fluxo, contando o número total de passos.

    steps = 0

    while True:
        # O conjunto reached representa todos os nós
        # que o fluxo consegue alcançar no passo atual.
        reached = set()

        # Verifica cada um dos donos atuais do insumo.

        owners = [n for n in g.nodes if g.nodes[n]['owner']]

        for n in owners:
            # Deixa de ser dono do insumo.
            g.nodes[n]['owner'] = difusao ###
            
            try:
                # Escolhe aleatoriamente um dos sucessores.
                m = func_traj(g, n) ##
            except IndexError:
                continue
            
            # Deixa de ser dono do insumo.
            g.nodes[n]['owner'] = difusao ###
            
            # Incrementa o atributo 'passages' do nó.
            g.nodes[m]['passages'] += 1

            # Incrementa o atributo 'passages' da aresta.
            g.edges[n, m]['passages'] += 1

            # Registra que consegue alcançar esse nó.
            reached.add(m)

            
        # Todo nó alcançado passa a ser dono do insumo.

        for n in reached:
            g.nodes[n]['owner'] = True

        # Isso conclui o passo atual da simulação.
        steps += 1

        # Se o passo alcançou t, chegamos ao fim da simulação.
        # Ela foi bem-sucedida: devolvemos o número de passos.
        if t in reached:
            return steps

        # Se o passo não alcançou ninguém, chegamos ao fim da
        # simulação. Ela não foi bem-sucedida: devolvemos -1.
        if not reached:
            return -1

In [7]:
def simulate_successful_flow(g, s, t, func_traj, difusao):
    set_geodesic_successors(g, s, t)

    while True:
        steps = simulate_single_flow(g, s, t, func_traj, difusao)

        if steps != -1:
            return steps

In [8]:
def simulate_all_flows(g,func_traj, difusao):
    for n in g.nodes:
        g.nodes[n]['closeness'] = 0
        g.nodes[n]['betweenness'] = 0

    for s, t in permutations(g.nodes, 2):
        steps = simulate_successful_flow(g, s, t, func_traj, difusao)

        g.nodes[s]['closeness'] += steps
        for n in g.nodes:
            if n != s and n != t:
                g.nodes[n]['betweenness'] += g.nodes[n]['passages']

    # Normalizações necessárias para comparar com os
    # resultados analíticos. Não precisa entender.
    for n in g.nodes:
        g.nodes[n]['closeness'] = (g.number_of_nodes() - 1) / g.nodes[n]['closeness']
        g.nodes[n]['betweenness'] /= (g.number_of_nodes() - 1) * (g.number_of_nodes() - 2)

In [13]:
# TIMES = 1000
# func_traj = random_geodesic_successor
# difusao = False

# func_traj = [random_geodesic_successor,random_path_successor,random_trail_successor,random_walk_successor]
# difusao =[False,True]

def simul(TIMES, func_traj, difusao):
    
    lista_closeness = [[], [], [], [], [], [], [], [], [], [], [], [] ,[], [], []]
    lista_betweenness = [[], [], [], [], [], [], [], [], [], [], [], [] ,[], [], []]
    
    for n in g.nodes:
        g.nodes[n]['mean_closeness'] = 0
        g.nodes[n]['mean_betweenness'] = 0

    for _ in range(TIMES):
        simulate_all_flows(g, func_traj, difusao)
        i = 0
        for n in g.nodes:
            g.nodes[n]['mean_closeness'] += g.nodes[n]['closeness']
            g.nodes[n]['mean_betweenness'] += g.nodes[n]['betweenness']
            lista_closeness[i].append(g.nodes[n]['closeness'])
            lista_betweenness[i].append(g.nodes[n]['betweenness'])
            i += 1

    for n in g.nodes:
        g.nodes[n]['mean_closeness'] /= TIMES
        g.nodes[n]['mean_betweenness'] /= TIMES

    df = pd.DataFrame({
    'família': [g.nodes[n]['label'] for n in g.nodes],
    'closeness simulado': [g.nodes[n]['mean_closeness'] for n in g.nodes],
    'betweenness simulado': [g.nodes[n]['mean_betweenness'] for n in g.nodes]})
    
    return df, lista_closeness, lista_betweenness

In [14]:
cc = nx.closeness_centrality(g)
bc = nx.betweenness_centrality(g)

In [15]:
bm, bmcl, bmbl = simul(100, random_geodesic_successor, False)
bmc = bm["closeness simulado"]
bmb = bm["betweenness simulado"]
bm.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.115751            0.411834
std                0.136353            0.074293
min                0.000000            0.285714
25%                0.010907            0.359211
50%                0.089121            0.400000
75%                0.132115            0.474713
max                0.521593            0.560000

In [12]:
bm.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.521648            0.560000     medici
3               0.256868            0.466667   guadagni
2               0.212967            0.482759    albizzi
5               0.142857            0.388889   salviati
8               0.121209            0.400000   bischeri
13              0.115000            0.437500  barbadori
9               0.089615            0.482759    ridolfi
7               0.087912            0.482759  tornabuon
14              0.087582            0.388889  castellan
11              0.078242            0.424242    strozzi
12              0.022363            0.350000    peruzzi
0               0.000000            0.333333     ginori
1               0.000000            0.325581  lambertes
4               0.000000            0.285714      pazzi
10              0.000000            0.368421  acciaiuol

In [13]:
bm.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.521648            0.560000     medici
2               0.212967            0.482759    albizzi
7               0.087912            0.482759  tornabuon
9               0.089615            0.482759    ridolfi
3               0.256868            0.466667   guadagni
13              0.115000            0.437500  barbadori
11              0.078242            0.424242    strozzi
8               0.121209            0.400000   bischeri
5               0.142857            0.388889   salviati
14              0.087582            0.388889  castellan
10              0.000000            0.368421  acciaiuol
12              0.022363            0.350000    peruzzi
0               0.000000            0.333333     ginori
1               0.000000            0.325581  lambertes
4               0.000000            0.285714      pazzi

In [17]:
gd, gdcl, gdbl = simul(100, random_geodesic_successor, True)
gdc = gd["closeness simulado"]
gdb = gd["betweenness simulado"]
gd.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.311440            0.411834
std                0.364073            0.074293
min                0.000000            0.285714
25%                0.028324            0.359211
50%                0.244341            0.400000
75%                0.361648            0.474713
max                1.386648            0.560000

In [15]:
gd.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               1.387637            0.560000     medici
3               0.689560            0.466667   guadagni
2               0.568132            0.482759    albizzi
5               0.406593            0.388889   salviati
13              0.317747            0.437500  barbadori
8               0.314560            0.400000   bischeri
9               0.249066            0.482759    ridolfi
7               0.248462            0.482759  tornabuon
14              0.230385            0.388889  castellan
11              0.201868            0.424242    strozzi
12              0.058187            0.350000    peruzzi
0               0.000000            0.333333     ginori
1               0.000000            0.325581  lambertes
4               0.000000            0.285714      pazzi
10              0.000000            0.368421  acciaiuol

In [16]:
gd.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               1.387637            0.560000     medici
2               0.568132            0.482759    albizzi
7               0.248462            0.482759  tornabuon
9               0.249066            0.482759    ridolfi
3               0.689560            0.466667   guadagni
13              0.317747            0.437500  barbadori
11              0.201868            0.424242    strozzi
8               0.314560            0.400000   bischeri
5               0.406593            0.388889   salviati
14              0.230385            0.388889  castellan
10              0.000000            0.368421  acciaiuol
12              0.058187            0.350000    peruzzi
0               0.000000            0.333333     ginori
1               0.000000            0.325581  lambertes
4               0.000000            0.285714      pazzi

In [23]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],gdcl[i]))

Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=0.0, pvalue=1.0)

In [24]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],gdbl[i]))

Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-115.31211986135911, pvalue=1.7351646660454248e-183)
Ttest_indResult(statistic=-177.34685230640127, pvalue=3.8671583400174212e-220)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-21140838588969296.0, pvalue=0.0)
Ttest_indResult(statistic=-426.06243456526704, pvalue=2.7578723652770939e-295)
Ttest_indResult(statistic=-49.698783434395878, pvalue=8.8630940398158954e-114)
Ttest_indResult(statistic=-120.21241778811307, pvalue=5.1377598032555071e-187)
Ttest_indResult(statistic=-78.963126508624015, pvalue=1.2460023645138965e-151)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-56.1821197016573, pvalue=1.2581318391292528e-123)
Ttest_indResult(statistic=-25.287561656791635, pvalue=6.4170504069670795e-64)
Ttest_indResult(statistic=-247.27996489850639, pvalue=1.358948367013882e-248)
Ttest_indResult(statistic=-142.48811336212043, pvalue=1.8178505056827609e-201)

In [25]:
pt, ptcl, ptbl = simul(100, random_path_successor, False)
ptc = pt["closeness simulado"]
ptb = pt["betweenness simulado"]
pt.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.246956            0.244090
std                0.187340            0.027643
min                0.000000            0.201416
25%                0.071429            0.230934
50%                0.246813            0.245924
75%                0.368571            0.259731
max                0.624396            0.311179

In [20]:
pt.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.629231            0.308820     medici
3               0.409286            0.269459   guadagni
14              0.383516            0.252257  castellan
11              0.368626            0.234387    strozzi
8               0.366593            0.247970   bischeri
9               0.361868            0.254059    ridolfi
7               0.333187            0.260004  tornabuon
12              0.246374            0.221332    peruzzi
13              0.241154            0.236175  barbadori
2               0.230824            0.259639    albizzi
5               0.142857            0.249435   salviati
0               0.000000            0.207852     ginori
1               0.000000            0.214419  lambertes
4               0.000000            0.199068      pazzi
10              0.000000            0.238304  acciaiuol

In [21]:
pt.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.629231            0.308820     medici
3               0.409286            0.269459   guadagni
7               0.333187            0.260004  tornabuon
2               0.230824            0.259639    albizzi
9               0.361868            0.254059    ridolfi
14              0.383516            0.252257  castellan
5               0.142857            0.249435   salviati
8               0.366593            0.247970   bischeri
10              0.000000            0.238304  acciaiuol
13              0.241154            0.236175  barbadori
11              0.368626            0.234387    strozzi
12              0.246374            0.221332    peruzzi
1               0.000000            0.214419  lambertes
0               0.000000            0.207852     ginori
4               0.000000            0.199068      pazzi

In [26]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],ptcl[i]))

Ttest_indResult(statistic=44.5936783854781, pvalue=3.2078838368393867e-105)
Ttest_indResult(statistic=46.943258570794001, pvalue=2.9552210069579546e-109)
Ttest_indResult(statistic=55.306418063954645, pvalue=2.3446404662926527e-122)
Ttest_indResult(statistic=52.322274123333955, pvalue=6.8490449817790757e-118)
Ttest_indResult(statistic=41.472380307980337, pvalue=1.3971608830648014e-99)
Ttest_indResult(statistic=49.752351152794311, pvalue=7.2741861432862656e-114)
Ttest_indResult(statistic=51.57460399767767, pvalue=9.7518690120892796e-117)
Ttest_indResult(statistic=54.29097866677224, pvalue=7.3360817194903198e-121)
Ttest_indResult(statistic=53.825822216229056, pvalue=3.619686159607666e-120)
Ttest_indResult(statistic=62.612522781216292, pvalue=1.8885574109934754e-132)
Ttest_indResult(statistic=49.159010516979521, pvalue=6.555083711408165e-113)
Ttest_indResult(statistic=64.379200716851471, pvalue=9.8833222101360827e-135)
Ttest_indResult(statistic=57.274148062479966, pvalue=3.465974939129898e-125)
Ttest_indResult(statistic=62.373759835348565, pvalue=3.8805540837303919e-132)
Ttest_indResult(statistic=47.510085506312421, pvalue=3.3284062893884499e-110)

In [27]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],ptbl[i]))

Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-9.4815477516806563, pvalue=8.0557931643643283e-18)
Ttest_indResult(statistic=-49.055843543279366, pvalue=9.6292353187518145e-113)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=-37.583215000377855, pvalue=4.5923516842164328e-92)
Ttest_indResult(statistic=-67.657074004486034, pvalue=8.1158007176806411e-139)
Ttest_indResult(statistic=-74.025500321819095, pvalue=2.9302514954942588e-146)
Ttest_indResult(statistic=-80.425153225903017, pvalue=3.6762443019705586e-153)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-90.232630621343944, pvalue=8.5706106637922224e-163)
Ttest_indResult(statistic=-69.832807851211371, pvalue=1.9792883517828923e-141)
Ttest_indResult(statistic=-37.658726984088972, pvalue=3.2397679835993067e-92)
Ttest_indResult(statistic=-96.589875109832036, pvalue=1.6145114643137195e-168)

In [28]:
pd1, pdcl,pdbl = simul(100, random_path_successor, True)
pdc = pd1["closeness simulado"]
pdb = pd1["betweenness simulado"]
pd1.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.562982            0.252551
std                0.157058            0.020954
min                0.259615            0.206732
25%                0.423049            0.236361
50%                0.609615            0.258264
75%                0.675659            0.266359
max                0.818681            0.283695

In [25]:
pd1.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.822582            0.268535     medici
3               0.742473            0.262201   guadagni
9               0.699890            0.274840    ridolfi
11              0.682582            0.264549    strozzi
7               0.682418            0.281837  tornabuon
8               0.649066            0.265617   bischeri
2               0.616813            0.256882    albizzi
14              0.615495            0.256510  castellan
13              0.579286            0.265430  barbadori
12              0.521538            0.252120    peruzzi
5               0.435440            0.223532   salviati
1               0.402692            0.234077  lambertes
10              0.395275            0.235336  acciaiuol
0               0.391099            0.229901     ginori
4               0.262363            0.202865      pazzi

In [26]:
pd1.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
7               0.682418            0.281837  tornabuon
9               0.699890            0.274840    ridolfi
6               0.822582            0.268535     medici
8               0.649066            0.265617   bischeri
13              0.579286            0.265430  barbadori
11              0.682582            0.264549    strozzi
3               0.742473            0.262201   guadagni
2               0.616813            0.256882    albizzi
14              0.615495            0.256510  castellan
12              0.521538            0.252120    peruzzi
10              0.395275            0.235336  acciaiuol
1               0.402692            0.234077  lambertes
0               0.391099            0.229901     ginori
5               0.435440            0.223532   salviati
4               0.262363            0.202865      pazzi

In [29]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],pdcl[i]))

Ttest_indResult(statistic=75.056421109200215, pvalue=2.0813162975236024e-147)
Ttest_indResult(statistic=73.554080393409123, pvalue=9.9332590414260126e-146)
Ttest_indResult(statistic=109.24296451111371, pvalue=6.5622489589674875e-179)
Ttest_indResult(statistic=108.21659139507761, pvalue=4.1254765585379603e-178)
Ttest_indResult(statistic=67.429963814753833, pvalue=1.5363886810891066e-138)
Ttest_indResult(statistic=114.16895525546313, pvalue=1.211830230516453e-182)
Ttest_indResult(statistic=126.86688090237961, pvalue=1.3705483128201531e-191)
Ttest_indResult(statistic=107.84739442095825, pvalue=8.0253961019728023e-178)
Ttest_indResult(statistic=85.451107952252443, pvalue=3.1493346396489795e-158)
Ttest_indResult(statistic=145.12252872439004, pvalue=5.0014692679165428e-203)
Ttest_indResult(statistic=82.527228558268035, pvalue=2.5745212806409542e-155)
Ttest_indResult(statistic=117.50654154358443, pvalue=4.380547434441444e-185)
Ttest_indResult(statistic=93.028181689623111, pvalue=2.3415208189750729e-165)
Ttest_indResult(statistic=115.29007912857, pvalue=1.8011024490993865e-183)
Ttest_indResult(statistic=101.51107262480278, pvalue=1.0448080980553311e-172)

In [30]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],pdbl[i]))

Ttest_indResult(statistic=-163.60586042384656, pvalue=2.9884806247716083e-213)
Ttest_indResult(statistic=-164.33911111123248, pvalue=1.2408410092987958e-213)
Ttest_indResult(statistic=-144.86482443213109, pvalue=7.0878337110132644e-203)
Ttest_indResult(statistic=-197.53202564417271, pvalue=2.3450222687043186e-229)
Ttest_indResult(statistic=-117.4320161953391, pvalue=4.9580951587214238e-185)
Ttest_indResult(statistic=-115.69459316774849, pvalue=9.0936642027730474e-184)
Ttest_indResult(statistic=-154.62858301913008, pvalue=1.9531294202432625e-208)
Ttest_indResult(statistic=-187.6408277364803, pvalue=5.8102800395141509e-225)
Ttest_indResult(statistic=-188.72915655057449, pvalue=1.8605435459810413e-225)
Ttest_indResult(statistic=-222.41239890989689, pvalue=1.6388526898706801e-239)
Ttest_indResult(statistic=-145.66810709333717, pvalue=2.3955661789456973e-203)
Ttest_indResult(statistic=-200.72276002840511, pvalue=9.9783207022244552e-231)
Ttest_indResult(statistic=-163.7346646393971, pvalue=2.5601909410946477e-213)
Ttest_indResult(statistic=-172.96630710471823, pvalue=5.3007440758645853e-218)
Ttest_indResult(statistic=-176.88871227272946, pvalue=6.4332436423988997e-220)

In [31]:
tt,ttcl, ttbl = simul(100, random_trail_successor, False)
ttc = tt["closeness simulado"]
ttb = tt["betweenness simulado"]
tt.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.247949            0.239472
std                0.196005            0.024436
min                0.000000            0.195081
25%                0.071429            0.224422
50%                0.268352            0.240537
75%                0.340330            0.257041
max                0.705824            0.285890

In [30]:
tt.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.702033            0.284393     medici
3               0.410879            0.254393   guadagni
14              0.377088            0.225952  castellan
8               0.350549            0.229280   bischeri
11              0.335989            0.231015    strozzi
9               0.335659            0.240283    ridolfi
7               0.318681            0.251080  tornabuon
2               0.267637            0.272878    albizzi
13              0.266044            0.261394  barbadori
12              0.230604            0.240766    peruzzi
5               0.142857            0.243996   salviati
0               0.000000            0.217355     ginori
1               0.000000            0.209079  lambertes
4               0.000000            0.192910      pazzi
10              0.000000            0.222337  acciaiuol

In [33]:
tt.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               0.705824            0.285890     medici
2               0.264945            0.269691    albizzi
13              0.268352            0.262431  barbadori
3               0.406703            0.262142   guadagni
7               0.320000            0.251941  tornabuon
9               0.335714            0.248135    ridolfi
5               0.142857            0.241378   salviati
12              0.225989            0.240537    peruzzi
11              0.330549            0.229732    strozzi
14              0.373352            0.228791  castellan
8               0.344945            0.228006   bischeri
10              0.000000            0.220837  acciaiuol
0               0.000000            0.217842     ginori
1               0.000000            0.209647  lambertes
4               0.000000            0.195081      pazzi

In [34]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],ttcl[i]))

Ttest_indResult(statistic=41.869656240938255, pvalue=2.564095272744433e-100)
Ttest_indResult(statistic=42.018888500814306, pvalue=1.3607734146286462e-100)
Ttest_indResult(statistic=56.107095439743667, pvalue=1.6138947095115394e-123)
Ttest_indResult(statistic=49.332569375659503, pvalue=3.4377969475400544e-113)
Ttest_indResult(statistic=40.631253662529822, pvalue=5.2826146390656007e-98)
Ttest_indResult(statistic=48.959815281829272, pvalue=1.3782146060756761e-112)
Ttest_indResult(statistic=53.318887292807212, pvalue=2.0898613453751597e-119)
Ttest_indResult(statistic=60.230521391253461, pvalue=2.7911137179745895e-129)
Ttest_indResult(statistic=68.048450211200105, pvalue=2.7144721049284645e-139)
Ttest_indResult(statistic=64.405527908318561, pvalue=9.1482844577715156e-135)
Ttest_indResult(statistic=48.217919726058092, pvalue=2.2450024956390702e-111)
Ttest_indResult(statistic=62.934688534753946, pvalue=7.1749659091594351e-133)
Ttest_indResult(statistic=42.440712762799983, pvalue=2.2921881262323797e-101)
Ttest_indResult(statistic=52.542287081855982, pvalue=3.1544471537035337e-118)
Ttest_indResult(statistic=52.821106521813284, pvalue=1.1856896310108792e-118)

In [32]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],ttbl[i]))

Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-20.139359002926522, pvalue=8.21211565463608e-50)
Ttest_indResult(statistic=-43.135402507353035, pvalue=1.2580600056947449e-102)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=0.0, pvalue=1.0)
Ttest_indResult(statistic=-49.736619273356936, pvalue=7.708580992629232e-114)
Ttest_indResult(statistic=-65.056616361893248, pvalue=1.3653518026324066e-135)
Ttest_indResult(statistic=-61.206689082483322, pvalue=1.3595878867949619e-130)
Ttest_indResult(statistic=-70.219265254274305, pvalue=6.9226718164375338e-142)
Ttest_indResult(statistic=nan, pvalue=nan)
Ttest_indResult(statistic=-75.337556515214899, pvalue=1.0178220719085429e-147)
Ttest_indResult(statistic=-67.750875975733194, pvalue=6.238822267575892e-139)
Ttest_indResult(statistic=-53.923597811161862, pvalue=2.5853901318010288e-120)
Ttest_indResult(statistic=-92.428539666867678, pvalue=8.1868189566961649e-165)

In [35]:
td, tdcl, tdbl = simul(100, random_trail_successor, True)
tdc = td["closeness simulado"]
tdb = td["betweenness simulado"]
td.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               0.681176            0.241101
std                0.280276            0.017554
min                0.261538            0.200127
25%                0.407555            0.229383
50%                0.689286            0.245211
75%                0.893846            0.252630
max                1.255220            0.263474

In [35]:
td.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               1.254670            0.256046     medici
7               0.931154            0.266526  tornabuon
9               0.927747            0.263413    ridolfi
3               0.892198            0.252381   guadagni
11              0.885440            0.251288    strozzi
14              0.827308            0.242259  castellan
8               0.784835            0.248592   bischeri
2               0.685110            0.246627    albizzi
13              0.605330            0.255634  barbadori
12              0.591648            0.238424    peruzzi
5               0.421758            0.218521   salviati
1               0.398736            0.226123  lambertes
0               0.374835            0.223289     ginori
10              0.371319            0.229390  acciaiuol
4               0.265000            0.200229      pazzi

In [36]:
td.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
7               0.931154            0.266526  tornabuon
9               0.927747            0.263413    ridolfi
6               1.254670            0.256046     medici
13              0.605330            0.255634  barbadori
3               0.892198            0.252381   guadagni
11              0.885440            0.251288    strozzi
8               0.784835            0.248592   bischeri
2               0.685110            0.246627    albizzi
14              0.827308            0.242259  castellan
12              0.591648            0.238424    peruzzi
10              0.371319            0.229390  acciaiuol
1               0.398736            0.226123  lambertes
0               0.374835            0.223289     ginori
5               0.421758            0.218521   salviati
4               0.265000            0.200229      pazzi

In [36]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],tdcl[i]))

Ttest_indResult(statistic=79.178919554307654, pvalue=7.3792124778866544e-152)
Ttest_indResult(statistic=90.710752352217526, pvalue=3.0849765251481416e-163)
Ttest_indResult(statistic=124.64913193623498, pvalue=4.3123838662962363e-190)
Ttest_indResult(statistic=121.1505988426662, pvalue=1.1251266277066391e-187)
Ttest_indResult(statistic=85.687591718864624, pvalue=1.84840596975027e-158)
Ttest_indResult(statistic=97.981147754608756, pvalue=1.0077558162694457e-169)
Ttest_indResult(statistic=130.72207789620506, pvalue=3.9172586265424182e-194)
Ttest_indResult(statistic=110.06688322719509, pvalue=1.5182933562406254e-179)
Ttest_indResult(statistic=104.04541470955033, pvalue=8.6572400224870059e-175)
Ttest_indResult(statistic=111.84660347888065, pvalue=6.6647888381790857e-181)
Ttest_indResult(statistic=81.742992700721359, pvalue=1.6160466880072504e-154)
Ttest_indResult(statistic=117.7029377332785, pvalue=3.1618690876088718e-185)
Ttest_indResult(statistic=83.187809333539519, pvalue=5.5495526159615762e-156)
Ttest_indResult(statistic=90.856017656674126, pvalue=2.2639563559341347e-163)
Ttest_indResult(statistic=94.409244356903542, pvalue=1.3492724313915364e-166)

In [37]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],tdbl[i]))

Ttest_indResult(statistic=-128.95778490591229, pvalue=5.5970295518622797e-193)
Ttest_indResult(statistic=-149.74652954100125, pvalue=1.062160158949307e-205)
Ttest_indResult(statistic=-126.08816407559205, pvalue=4.5697654199167638e-191)
Ttest_indResult(statistic=-160.6180228111607, pvalue=1.1183130009179397e-211)
Ttest_indResult(statistic=-95.296307561299642, pvalue=2.2036532423134584e-167)
Ttest_indResult(statistic=-99.283387163138073, pvalue=7.7722352769123287e-171)
Ttest_indResult(statistic=-157.18666223036044, pvalue=7.7829482445830029e-210)
Ttest_indResult(statistic=-197.79239638039328, pvalue=1.809024391340956e-229)
Ttest_indResult(statistic=-166.98192980520858, pvalue=5.3906788650250429e-215)
Ttest_indResult(statistic=-188.57322748138651, pvalue=2.1893923685065092e-225)
Ttest_indResult(statistic=-131.34552262800605, pvalue=1.5434402941580046e-194)
Ttest_indResult(statistic=-211.93532568486452, pvalue=2.2206565338707752e-235)
Ttest_indResult(statistic=-145.62223490368726, pvalue=2.5482518322652382e-203)
Ttest_indResult(statistic=-136.60816116664697, pvalue=7.0312731916008878e-198)
Ttest_indResult(statistic=-172.16421768684685, pvalue=1.3225032048466926e-217)

In [38]:
wt,wtcl,wtbl = simul(100, random_walk_successor, False)
wtc = wt["closeness simulado"]
wtb = wt["betweenness simulado"]
wt.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               2.063821            0.036326
std                1.168130            0.002457
min                0.715989            0.033989
25%                1.173159            0.034317
50%                2.434890            0.035981
75%                2.481813            0.036896
max                5.055385            0.042036

In [40]:
wt.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               5.109011            0.034522     medici
3               3.331044            0.036129   guadagni
9               2.518407            0.035169    ridolfi
11              2.499945            0.035760    strozzi
7               2.492802            0.033212  tornabuon
2               2.483626            0.036084    albizzi
8               2.468297            0.033771   bischeri
14              2.454560            0.032256  castellan
12              1.612418            0.034330    peruzzi
13              1.611593            0.034076  barbadori
5               1.587857            0.038615   salviati
10              0.776813            0.038243  acciaiuol
1               0.765714            0.036976  lambertes
0               0.752967            0.037620     ginori
4               0.733352            0.040273      pazzi

In [41]:
wt.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
4               0.733352            0.040273      pazzi
5               1.587857            0.038615   salviati
10              0.776813            0.038243  acciaiuol
0               0.752967            0.037620     ginori
1               0.765714            0.036976  lambertes
3               3.331044            0.036129   guadagni
2               2.483626            0.036084    albizzi
11              2.499945            0.035760    strozzi
9               2.518407            0.035169    ridolfi
6               5.109011            0.034522     medici
12              1.612418            0.034330    peruzzi
13              1.611593            0.034076  barbadori
8               2.468297            0.033771   bischeri
7               2.492802            0.033212  tornabuon
14              2.454560            0.032256  castellan

In [39]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],wtcl[i]))

Ttest_indResult(statistic=231.70654722010161, pvalue=5.1008927956870526e-243)
Ttest_indResult(statistic=234.4734508636721, pvalue=4.9042340783252583e-244)
Ttest_indResult(statistic=388.96468284967045, pvalue=1.8397077609721324e-287)
Ttest_indResult(statistic=314.09374622861003, pvalue=4.1629386933983876e-269)
Ttest_indResult(statistic=208.73595692597263, pvalue=4.4533498349079799e-234)
Ttest_indResult(statistic=258.68880019788588, pvalue=1.8473680722125444e-252)
Ttest_indResult(statistic=493.30564774953029, pvalue=7.0979679095980394e-308)
Ttest_indResult(statistic=461.79362964742819, pvalue=3.3305770793209315e-302)
Ttest_indResult(statistic=320.56192193495747, pvalue=7.4130979825412045e-271)
Ttest_indResult(statistic=420.54410817120322, pvalue=3.6337737071202994e-294)
Ttest_indResult(statistic=262.77713844173263, pvalue=8.3575591804545606e-254)
Ttest_indResult(statistic=394.08675645550471, pvalue=1.3842743532039595e-288)
Ttest_indResult(statistic=312.53628475263844, pvalue=1.1117190339393083e-268)
Ttest_indResult(statistic=349.84873444060725, pvalue=2.3198585014066377e-278)
Ttest_indResult(statistic=307.54442333664389, pvalue=2.6772906642946736e-267)

In [40]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],wtbl[i]))

Ttest_indResult(statistic=-58.491606028774704, pvalue=6.7850168031200877e-127)
Ttest_indResult(statistic=-66.846879933738165, pvalue=7.9808000105543762e-138)
Ttest_indResult(statistic=-77.831607203898258, pvalue=1.9865730317779804e-150)
Ttest_indResult(statistic=-86.171518293880482, pvalue=6.238942143152611e-159)
Ttest_indResult(statistic=-69.12951902497089, pvalue=1.357653406835872e-140)
Ttest_indResult(statistic=-79.556682941161185, pvalue=2.958935559278561e-152)
Ttest_indResult(statistic=-90.659300482093059, pvalue=3.4426969579843153e-163)
Ttest_indResult(statistic=-89.90603038994449, pvalue=1.7275456517578823e-162)
Ttest_indResult(statistic=-77.737053247745152, pvalue=2.5080595577739168e-150)
Ttest_indResult(statistic=-83.548580536988894, pvalue=2.4120985142521115e-156)
Ttest_indResult(statistic=-73.20742696362916, pvalue=2.4489423524747416e-145)
Ttest_indResult(statistic=-78.836709427172764, pvalue=1.6946134455258373e-151)
Ttest_indResult(statistic=-73.948931791540858, pvalue=3.5711194459217786e-146)
Ttest_indResult(statistic=-80.834855726006865, pvalue=1.3845654728181507e-153)
Ttest_indResult(statistic=-79.357373981803534, pvalue=4.7896788743555967e-152)

In [41]:
wd,wdcl,wdbl = simul(100, random_walk_successor, True)
wdc = wd["closeness simulado"]
wdb = wd["betweenness simulado"]
wd.describe()

       betweenness simulado  closeness simulado
count             15.000000           15.000000
mean               2.375601            0.155120
std                1.664882            0.012317
min                0.578516            0.129218
25%                1.140742            0.144924
50%                2.391209            0.155580
75%                2.895989            0.164806
max                6.886264            0.172718

In [45]:
wd.sort_values('betweenness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
6               6.906758            0.168225     medici
3               4.497088            0.164223   guadagni
14              3.105714            0.150862  castellan
2               3.052253            0.159994    albizzi
8               2.773901            0.156368   bischeri
11              2.694890            0.157176    strozzi
9               2.550934            0.169441    ridolfi
7               2.414066            0.168983  tornabuon
5               1.827747            0.143511   salviati
12              1.679560            0.145375    peruzzi
13              1.475604            0.165650  barbadori
0               0.808516            0.142492     ginori
4               0.786374            0.128925      pazzi
1               0.698626            0.143679  lambertes
10              0.575824            0.152345  acciaiuol

In [46]:
wd.sort_values('closeness simulado', ascending=0)

    betweenness simulado  closeness simulado    família
9               2.550934            0.169441    ridolfi
7               2.414066            0.168983  tornabuon
6               6.906758            0.168225     medici
13              1.475604            0.165650  barbadori
3               4.497088            0.164223   guadagni
2               3.052253            0.159994    albizzi
11              2.694890            0.157176    strozzi
8               2.773901            0.156368   bischeri
10              0.575824            0.152345  acciaiuol
14              3.105714            0.150862  castellan
12              1.679560            0.145375    peruzzi
1               0.698626            0.143679  lambertes
5               1.827747            0.143511   salviati
0               0.808516            0.142492     ginori
4               0.786374            0.128925      pazzi

In [42]:
for i in range(15):
    print(stats.ttest_ind(bmcl[i],wdcl[i]))

Ttest_indResult(statistic=105.9780911157583, pvalue=2.4127702100947272e-176)
Ttest_indResult(statistic=101.68610097434829, pvalue=7.4760359166250423e-173)
Ttest_indResult(statistic=128.65967142008409, pvalue=8.8031368102026505e-193)
Ttest_indResult(statistic=154.2757781445406, pvalue=3.0587519959967099e-208)
Ttest_indResult(statistic=114.62772482225263, pvalue=5.5425536321853361e-183)
Ttest_indResult(statistic=142.79490322823523, pvalue=1.1923006092585229e-201)
Ttest_indResult(statistic=136.97526264752582, pvalue=4.1559461933297763e-198)
Ttest_indResult(statistic=113.51158766362289, pvalue=3.7372907853244104e-182)
Ttest_indResult(statistic=119.37131313219916, pvalue=2.0247470002940792e-186)
Ttest_indResult(statistic=119.92990881068542, pvalue=8.1352061951768195e-187)
Ttest_indResult(statistic=107.40316413450229, pvalue=1.7925124387002724e-177)
Ttest_indResult(statistic=126.09368097728479, pvalue=4.5308281440621683e-191)
Ttest_indResult(statistic=96.299087960520893, pvalue=2.8968862171284099e-168)
Ttest_indResult(statistic=113.47420115337469, pvalue=3.9852619840441525e-182)
Ttest_indResult(statistic=107.06799125566162, pvalue=3.2938583468476011e-177)

In [43]:
for i in range(15):
    print(stats.ttest_ind(bmbl[i],wdbl[i]))

Ttest_indResult(statistic=-80.776533441101009, pvalue=1.5905976365768901e-153)
Ttest_indResult(statistic=-79.171679292471666, pvalue=7.5098959560355134e-152)
Ttest_indResult(statistic=-90.280980841516566, pvalue=7.7274230266524729e-163)
Ttest_indResult(statistic=-95.537866652985954, pvalue=1.3491474787632221e-167)
Ttest_indResult(statistic=-87.71658559104516, pvalue=2.0219367986945478e-160)
Ttest_indResult(statistic=-92.712346110477128, pvalue=4.5227890645691812e-165)
Ttest_indResult(statistic=-106.38539168494842, pvalue=1.1437503288145427e-176)
Ttest_indResult(statistic=-116.35595866184532, pvalue=2.9898296081292715e-184)
Ttest_indResult(statistic=-101.51689275881257, pvalue=1.0332344924248756e-172)
Ttest_indResult(statistic=-118.61241149439374, pvalue=7.0351359583685072e-186)
Ttest_indResult(statistic=-94.697612554249559, pvalue=7.4731001451433572e-167)
Ttest_indResult(statistic=-103.74198608159446, pvalue=1.527632616002838e-174)
Ttest_indResult(statistic=-107.7128584239488, pvalue=1.023325011114393e-177)
Ttest_indResult(statistic=-93.728891614331658, pvalue=5.4762349224967845e-166)
Ttest_indResult(statistic=-91.897923590092518, pvalue=2.4944315328964367e-164)